%.pdf: %.tex
	pdflatex $<

# clean:
# 	find -E . \( -name "*.aux" \
# 	          -o -name "$<.*" \
#                    ! -name "*.pdf" \
#                    ! -name "*.dvi" \
#                    ! -name "*.tex" \
#                    ! -name "*.bib" \) \
#             -exec rm -rf {} \;

# extraclean:
# 	find -E . \( -name "*.aux" \
# 	          -o -name "$(NAME).*" \
#                    ! -name "*.dvi" \
#                    ! -name "*.tex" \
#                    ! -name "*.bib" \) \
#             -exec rm -rf {} \;
