(require 'color-theme)

(defun color-theme-dimilar ()
  "A color theme based on Tango Palette."
  (interactive)
  (color-theme-install
   '(color-theme-dimilar
     ((background-mode . dark)
      (background-color . "#1e1e27")
      (foreground-color . "#CFBFAD")
      (cursor-color     . "#8B8BFF")
      (mouse-color      . "gold1"))
     ((help-highlight-face . underline)
      (ibuffer-dired-buffer-face . font-lock-function-name-face)
      (ibuffer-help-buffer-face . font-lock-comment-face)
      (ibuffer-hidden-buffer-face . font-lock-warning-face)
      (ibuffer-occur-match-face . font-lock-warning-face)
      (ibuffer-read-only-buffer-face . font-lock-type-face)
      (ibuffer-special-buffer-face . font-lock-keyword-face)
      (ibuffer-title-face . font-lock-type-face))
     (diary ((((min-colors 88) (class color) (background dark)) (:foreground "plum" :weight normal))))
     (mumamo-background-chunk-major ((((class color) (min-colors 88) (background dark)) nil)))
     (mumamo-background-chunk-submode1 ((((class color) (min-colors 88) (background dark)) nil)))
     (mumamo-background-chunk-submode2 ((((class color) (min-colors 88) (background dark)) nil)))
     (mumamo-background-chunk-submode3 ((((class color) (min-colors 88) (background dark)) nil)))
     (mumamo-background-chunk-submode4 ((((class color) (min-colors 88) (background dark)) nil)))
     (font-lock-builtin-face ((((class color) (min-colors 88) (background dark)) (:foreground "LightSteelBlue" :weight normal))))
     (font-lock-comment-delimiter-face ((default (:inherit font-lock-comment-face :slant italic)) (((class color) (min-colors 16)) nil)))
     (font-lock-comment-face ((((class color) (min-colors 88) (background dark)) (:foreground "RoyalBlue2" :slant italic))))
     (font-lock-constant-face ((((class color) (min-colors 88) (background dark)) (:foreground "Aquamarine" :weight normal))))
     (font-lock-function-name-face ((((class color) (min-colors 88) (background dark)) (:foreground "DeepPink" :weight normal :height 1.0 :width extra-expanded))))
     (font-lock-keyword-face ((((class color) (min-colors 88) (background dark)) (:foreground "#7ec0ee" :weight normal :height 1.0 :width extra-expanded))))
     (font-lock-negation-char-face ((t (:foreground "DeepSkyBlue" :weight normal))))
     (font-lock-preprocessor-face ((t (:inherit font-lock-builtin-face :foreground "violet"))))
     (font-lock-regexp-grouping-backslash ((t (:inherit bold :foreground "IndianRed"))))
     (font-lock-regexp-grouping-construct ((t (:inherit bold :foreground "BlueViolet"))))
     (font-lock-string-face ((((class color) (min-colors 88) (background dark)) (:foreground "LightSalmon1":weight bold))))
     (font-lock-type-face ((((class color) (min-colors 88) (background dark)) (:foreground "PaleGreen" :weight normal))))
     (font-lock-variable-name-face ((((class color) (min-colors 88) (background dark)) (:foreground "LightGoldenrod" :weight normal))))
     (holiday ((((class color) (background dark)) (:background "SteelBlue" :foreground "white" :weight semi-bold))))
     (info-xref ((t (:inherit link :foreground "SkyBlue1"))))
     (cparen-around-quote-face ((t (:foreground "SaddleBrown"))))
     ;; (cal-china-x-priority1-holidays t)
     ;; (cal-china-x-priority2-holidays t)
     (ac-selection-face ((t (:background "royal blue" :foreground "white"))))
     (company-template-field ((((background dark)) (:background "LightSkyBlue3" :foreground "black"))))
     (company-tooltip ((t (:background "lightgray" :foreground "black"))))
     (company-tooltip-selection ((t (:inherit company-tooltip :background "royal blue"))))
     (matlab-cross-function-variable-face ((t (:foreground "blue" :underline nil :slant italic :weight bold))))
     (matlab-nested-function-keyword-face ((t (:foreground "gold" :underline nil :slant italic))))
     (menu ((t (:background "pink" :foreground "LightGreen"))))
     ;; (diredp-display-msg ((t nil)))
     (minibuffer-prompt ((((background dark)) (:foreground "LightBlue"))))
     (diredp-exec-priv ((t (:background "LightSteelBlue" :foreground "black"))))
     (diredp-file-name ((t (:foreground "gray"))))
     (diredp-flag-mark-line ((t (:background "pink" :foreground "black"))))
     (diredp-no-priv ((t (:background "LightGray" :foreground "black"))))
     (diredp-other-priv ((t (:background "PaleGoldenrod" :foreground "black"))))
     (diredp-read-priv ((t (:background "MediumAquamarine" :foreground "black"))))
     (tooltip ((((class color)) (:stipple nil :background "SkyBlue" :foreground "black"))))
     (w3m-anchor ((((class color) (background dark)) (:foreground "LightSkyBlue" :weight normal))))
     (w3m-arrived-anchor ((((class color) (background dark)) (:foreground "LightSkyBlue" :weight normal))))
     (w3m-history-current-url ((t (:background "DodgerBlue4"))))
     (w3m-bold ((t (:foreground "white" :weight bold))))
     (w3m-current-anchor ((t (:foreground "pink" :underline t :weight bold))))
     (w3m-form-button ((((type x w32 mac) (class color)) (:background "LightGreen" :foreground "DeepPink" :box (:line-width 2 :style released-button) :weight normal))))
     (w3m-header-line-location-title ((((class color) (background dark)) (:background "Gray20" :foreground "SteelBlue" :weight normal))))
     (w3m-insert ((((class color) (background dark)) (:foreground "DeepPink"))))
     (w3m-italic ((t (:foreground "DodgerBlue1" :slant italic))))
     (w3m-strike-through ((((class color)) (:foreground "red" :strike-through t))))
     (woman-addition ((t (:foreground "pink"))))
     (woman-bold ((((background dark)) (:foreground "SkyBlue1" :weight bold))))
     (woman-italic ((((background dark)) (:foreground "DeepPink1" :underline t :slant italic))))
     (w3m-underline ((t (:foreground "pink" :underline t))))
     (gnus-cite-attribution-face ((t (:lforeground "lemon chiffon" :bold t))))
     (gnus-cite-face-1 ((t (:foreground "LightSalmon"))))
     (gnus-cite-face-2 ((t (:foreground "Khaki"))))
     (gnus-cite-face-3 ((t (:foreground "Coral"))))
     (gnus-cite-face-4 ((t (:foreground "yellow green"))))
     (gnus-cite-face-5 ((t (:foreground "dark khaki"))))
     (gnus-cite-face-6 ((t (:foreground "bisque"))))
     (gnus-cite-face-7 ((t (:foreground "peru"))))
     (gnus-cite-face-8 ((t (:foreground "light coral"))))
     (gnus-cite-face-9 ((t (:foreground "plum"))))
     (gnus-group-mail-1-empty-face ((t (:foreground "White"))))
     (gnus-group-mail-1-face ((t (:bold t :foreground "White"))))
     (gnus-group-mail-2-empty-face ((t (:foreground "light cyan"))))
     (gnus-group-mail-2-face ((t (:bold t :foreground "light cyan"))))
     (gnus-group-mail-3-empty-face ((t (:foreground "LightBlue"))))
     (gnus-group-mail-3-face ((t (:bold t :foreground "LightBlue"))))
     (gnus-group-mail-low-empty-face ((t (:foreground "Aquamarine"))))
     (gnus-group-mail-low-face ((t (:bold t :foreground "Aquamarine"))))
     (gnus-group-news-1-empty-face ((t (:foreground "White"))))
     (gnus-group-news-1-face ((t (:bold t :foreground "White"))))
     ;; (gnus-group-news-2-empty-face ((t (:foreground "light cyan"))))
     ;; (gnus-group-news-2-face ((t (:bold t :foreground "light cyan"))))
     ;; (gnus-group-news-3-empty-face ((t (:foreground "LightBlue"))))
     ;; (gnus-group-news-3-face ((t (:bold t :foreground "LightBlue"))))
     (gnus-group-news-4-empty-face ((t (:foreground "Aquamarine"))))
     (gnus-group-news-4-face ((t (:bold t :foreground "Aquamarine"))))
     (gnus-group-news-5-empty-face ((t (:foreground "MediumAquamarine"))))
     (gnus-group-news-5-face ((t (:bold t :foreground "MediumAquamarine"))))
     (gnus-group-news-6-empty-face ((t (:foreground "MediumAquamarine"))))
     (gnus-group-news-6-face ((t (:bold t :foreground "MediumAquamarine"))))
     (gnus-group-news-low-empty-face ((t (:foreground "MediumAquamarine"))))
     (gnus-group-news-low-face ((t (:bold t :foreground "MediumAquamarine"))))
     (gnus-emphasis-bold ((t (:bold t))))
     (gnus-emphasis-bold-italic ((t (:italic t :bold t))))
     (gnus-emphasis-highlight-words ((t (:background "black" :foreground "yellow"))))
     (gnus-emphasis-italic ((t (:italic t))))
     (gnus-emphasis-underline ((t (:underline t))))
     (gnus-emphasis-underline-bold ((t (:bold t :underline t))))
     (gnus-emphasis-underline-bold-italic ((t (:italic t :bold t :underline t))))
     (gnus-emphasis-underline-italic ((t (:italic t :underline t))))
     (gnus-header-content-face ((t (:foreground "LightSkyBlue3"))))
     (gnus-header-from-face ((t (:bold t :foreground "light cyan"))))
     (gnus-header-name-face ((t (:bold t :foreground "LightBlue"))))
     (gnus-header-newsgroups-face ((t (:bold t :foreground "MediumAquamarine"))))
     (gnus-header-subject-face ((t (:bold t :foreground "light cyan"))))
     (gnus-signature-face ((t (:foreground "Grey"))))
     (gnus-splash-face ((t (:foreground "ForestGreen"))))
     (gnus-summary-cancelled-face ((t (:background "Black" :foreground "Yellow"))))
     (gnus-summary-high-ancient-face ((t (:bold t :foreground "MediumAquamarine"))))
     (gnus-summary-high-read-face ((t (:bold t :foreground "Aquamarine"))))
     (gnus-summary-high-ticked-face ((t (:bold t :foreground "LightSalmon"))))
     (gnus-summary-high-unread-face ((t (:bold t :foreground "beige"))))
     (gnus-summary-low-ancient-face ((t (:foreground "DimGray"))))
     (gnus-summary-low-read-face ((t (:foreground "slate gray"))))
     (gnus-summary-low-ticked-face ((t (:foreground "Pink"))))
     (gnus-summary-low-unread-face ((t (:foreground "LightGray"))))
     (gnus-summary-normal-ancient-face ((t (:foreground "MediumAquamarine"))))
     (gnus-summary-normal-read-face ((t (:foreground "Aquamarine"))))
     (gnus-summary-normal-ticked-face ((t (:foreground "LightSalmon"))))
     (gnus-summary-normal-unread-face ((t (nil))))
     (gnus-summary-selected-face ((t (:background "DarkSlateBlue"))))
     (message-cited-text-face ((t (:foreground "LightSalmon"))))
     (message-header-cc-face ((t (:foreground "light cyan"))))
     (message-header-name-face ((t (:foreground "maroon1"))))
     (message-header-newsgroups-face ((t (:bold t :foreground "MediumAquamarine"))))
     (message-header-other-face ((t (:foreground "RoyalBlue1"))))
     (message-header-subject-face ((t (:bold t :foreground "DeepSkyBlue1"))))
     (message-header-to-face ((t (:bold t :foreground "PaleTurquoise1"))))
     (message-header-xheader-face ((t (:foreground "MediumAquamarine"))))
     (message-separator-face ((t (:foreground "steel blue")))))))

(provide 'color-theme-dilimar)