(require 'color-theme)

(defun color-theme-dimilartty ()
  "A color theme based on Tango Palette."
  (interactive)
  (color-theme-install
   '(color-theme-dimilartty
     ((help-highlight-face . underline)
      (ibuffer-dired-buffer-face . font-lock-function-name-face)
      (ibuffer-help-buffer-face . font-lock-comment-face)
      (ibuffer-hidden-buffer-face . font-lock-warning-face)
      (ibuffer-occur-match-face . font-lock-warning-face)
      (ibuffer-read-only-buffer-face . font-lock-type-face)
      (ibuffer-special-buffer-face . font-lock-keyword-face)
      (ibuffer-title-face . font-lock-type-face))
     (font-lock-builtin-face ((((class color) (min-colors 8)) (:foreground "magenta" :weight bold))))
     (font-lock-comment-face ((t (:foreground "blue" :slant italic :weight bold))))
     (font-lock-function-name-face ((((class color) (min-colors 8)) (:foreground "cyan" :weight bold))))
     (font-lock-variable-name-face ((((class color) (min-colors 8)) (:foreground "red" :weight light))))
     (info-menu-header ((((type tty pc)) (:foreground "cyan" :underline t :weight bold))))
     (info-node ((t (:foreground "magenta" :slant italic :weight bold))))
     (info-title-3 ((((type tty pc) (class color)) (:foreground "blue" :weight bold))))
     (info-title-4 ((((type tty pc) (class color)) (:foreground "cyan" :weight bold))))
     (info-xref ((t (:foreground "cyan"))))
     (info-xref-visited ((t (:foreground "red"))))
     (linum ((t (:foreground "magenta"))))
     (flymake-errline ((t (:background "red" :weight bold))))
     (flymake-warnline ((t (:background "yellow" :weight bold))))
     (org-code ((((class color grayscale) (min-colors 88) (background dark)) (:foreground "DeepSkyBlue4"))))
     (w3m-anchor ((t (:foreground "cyan" :underline t))))
     (w3m-arrived-anchor ((t (:foreground "green" :underline t))))
     (w3m-bold ((t (:foreground "white" :weight bold))))
     (w3m-current-anchor ((t (:foreground "magenta" :underline t :weight bold))))
     (w3m-form-button ((t (:foreground "blue" :underline t))))
     (w3m-form-button-mouse ((t (:foreground "cyan" :underline t))))
     (w3m-form-button-pressed ((t (:foreground "green" :underline t))))
     (w3m-header-line-location-content ((nil (:foreground "red"))))
     (w3m-header-line-location-title ((nil (:foreground "cyan"))))
     (w3m-history-current-url ((t (:background "DodgerBlue4"))))
     (w3m-italic ((t (:foreground "magenta" :slant italic))))
     (w3m-tab-background ((((class color)) (:background "white" :foreground "magenta"))))
     (w3m-tab-mouse ((nil (:foreground "blue"))))
     (w3m-underline ((t (:foreground "green" :underline t)))))))
(provide 'color-theme-dilimartty)