NAME=tex-beamer-unl
SOURCE=$(NAME).tex

pdf: $(SOURCE)
	pdflatex $(NAME)

clean:
	find -E . \( -name "*.aux" \
	          -o -name "$(NAME).*" \
                   ! -name "*.pdf" \
                   ! -name "*.dvi" \
                   ! -name "*.tex" \
                   ! -name "*.bib" \) \
            -exec rm -rf {} \;

extraclean:
	find -E . \( -name "*.aux" \
	          -o -name "$(NAME).*" \
                   ! -name "*.dvi" \
                   ! -name "*.tex" \
                   ! -name "logo.pdf" \
                   ! -name "*.bib" \) \
            -exec rm -rf {} \;
